# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8169a42eb813447cb7de200f7a5f8b415cb9d9d8b7d1ae63dce570bf12a3b55d1c6c1a006e07e4bfd32f0324e05aa2dc590eae8fbbb984d8c754aae9351fb6a

test:
  secret_key_base: f6e39a892aca41089f70ec9ae678df092199cd3f1c6eb4a638b32ed199c1de8ca4a308eaefb29be3f45142f89c5760914f6e63677934d3fb09fc2d6b6e0a7743

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
